### ISSUE TITLE
Unrecognized font family when using the library

### ISSUE THREAD

**Issue by pedrohperalta** [loadsmart/blocks#28]
Steps to reproduce:

1. Create a new RN app
2. Add this library to your project
3. Create a React.Component and add the following component to it:

```
<PrimaryButton title="Login" style={styles.loginButton} />
```

Got the following error:

![Simulator Screen Shot - iPhone X - 2019-07-24 at 13 07 51](https://user-images.githubusercontent.com/3199279/61809901-92face00-ae14-11e9-980f-e2a79cc00df4.png)

P.S. Already tried to run: `react-native link`, but didn't work.

**Comment by barbosa** [comment]
This should be fixed now on version `0.12.0`. Let me know if it persists.

<img width="512" alt="Screen Shot 2019-07-28 at 2 20 02 PM" src="https://user-images.githubusercontent.com/235208/62011280-3f55f080-b144-11e9-8a4f-1bdfad982c4b.png">
